// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzapsnrbpfgqdwyatfgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6YXBzbnJicGZncWR3eWF0ZmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NzAwMzAsImV4cCI6MjA1NTI0NjAzMH0.cQX79MM5V-TZiJSb76AX7WfMR_cSCbQHhTOnAMA321o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);